# Generated by Django 4.1.3 on 2022-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
